resources:
- ../../base
- job-pre-deployment.yaml
- job-post-deployment.yaml
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: simple-bash 
    patch: |-
      - op: add 
        path: /metadata/labels/environment
        value: dev 
