resources:
- ../../base
- pre-deployment-job.yaml
- post-deployment-job.yaml
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: simple-bash 
    patch: |-
      - op: add 
        path: /metadata/labels/environment
        value: dev 
