apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-bash
  name: simple-bash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bash
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-bash
    spec:
      volumes:
      - name: log-vol
        emptyDir: {} 
      containers:
      - image: quay.io/rh_ee_dagrant/simple-bash:1.2
        name: simple-bash
        resources: {}
        volumeMounts:
        - name: log-vol
          mountPath: /apps/logs
status: {}
